// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseWindow() {
  return window['go']['main']['App']['CloseWindow']();
}

export function HideToTray() {
  return window['go']['main']['App']['HideToTray']();
}

export function MinimizeWindow() {
  return window['go']['main']['App']['MinimizeWindow']();
}

export function QuitFromTray() {
  return window['go']['main']['App']['QuitFromTray']();
}

export function SaveWindowState() {
  return window['go']['main']['App']['SaveWindowState']();
}

export function ShowFromTray() {
  return window['go']['main']['App']['ShowFromTray']();
}

export function ShowMainWindow() {
  return window['go']['main']['App']['ShowMainWindow']();
}
