// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CloseWindow():Promise<void>;

export function GetDiscordSession():Promise<main.PublicDiscordSession>;

export function HideToTray():Promise<void>;

export function LogoutDiscord():Promise<main.PublicDiscordSession>;

export function MinimizeWindow():Promise<void>;

export function QuitFromTray():Promise<void>;

export function SaveWindowState():Promise<void>;

export function ShowFromTray():Promise<void>;

export function ShowMainWindow():Promise<void>;

export function StartDiscordLogin():Promise<main.PublicDiscordSession>;
