import test from 'node:test';import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
const source=await readFile(new URL('./shortcut-capture.js',import.meta.url),'utf8');
const {createShortcutCapture}=await import(`data:text/javascript;base64,${Buffer.from(source).toString('base64')}`);
const event=code=>({code,key:code,preventDefault(){}});
test('single key saves on release, not press',()=>{const saved=[];const capture=createShortcutCapture({save:s=>saved.push(s),cancel(){}});capture.start();capture.keydown(event('KeyM'));assert.deepEqual(saved,[]);capture.keyup(event('KeyM'));assert.deepEqual(saved,['M']);});
test('capture collects all keys until all are released and ignores repeats',()=>{const saved=[];const capture=createShortcutCapture({save:s=>saved.push(s),cancel(){}});capture.start();for(const key of ['ControlLeft','KeyM','KeyM','KeyN'])capture.keydown(event(key));capture.keyup(event('KeyM'));assert.deepEqual(saved,[]);capture.keyup(event('ControlLeft'));assert.deepEqual(saved,[]);capture.keyup(event('KeyN'));assert.deepEqual(saved,['Ctrl+M+N']);});
test('Escape and focus loss discard incomplete shortcuts',()=>{const saved=[];let cancelled=0;const capture=createShortcutCapture({save:s=>saved.push(s),cancel(){cancelled++}});capture.start();capture.keydown(event('KeyM'));capture.keydown(event('Escape'));capture.keyup(event('KeyM'));capture.start();capture.keydown(event('KeyN'));capture.cancel();capture.keyup(event('KeyN'));assert.deepEqual(saved,[]);assert.equal(cancelled,2);});
test('logical letters follow keyboard layout while release tracks physical code',()=>{const saved=[];const capture=createShortcutCapture({save:s=>saved.push(s),cancel(){}});capture.start();capture.keydown({...event('KeyQ'),key:'a'});capture.keyup({...event('KeyQ'),key:'A'});assert.deepEqual(saved,['A']);});
