import test from 'node:test';
import assert from 'node:assert/strict';
import {createConfigurationService,configurationCatalog} from './admin-configuration.js';
function memoryDB(){let value=null;return {async getConnection(){return this;},async beginTransaction(){},async commit(){},async rollback(){},release(){},async execute(sql,args){if(sql.startsWith('SELECT'))return [value?[{value}]:[]];if(sql.startsWith('INSERT')){if(args.length===2)value=args[1];else value ||= '{"revision":0,"overrides":{},"botDefaults":{}}';}return [{}];}};}
test('configuration saves overrides, preserves env defaults and deletes resets',async()=>{const env={GUILDSYNC_GOOGLE_SHEETS_ENABLED:'true'};const service=createConfigurationService(memoryDB(),{env});await service.initialize();let view=await service.save({revision:0,changes:{GUILDSYNC_GOOGLE_SHEETS_ENABLED:false}});assert.equal(env.GUILDSYNC_GOOGLE_SHEETS_ENABLED,'false');assert.equal(view.settings.find(s=>s.key==='GUILDSYNC_GOOGLE_SHEETS_ENABLED').defaultValue,true);view=await service.save({revision:1,changes:{GUILDSYNC_GOOGLE_SHEETS_ENABLED:null}});assert.equal(env.GUILDSYNC_GOOGLE_SHEETS_ENABLED,'true');assert.equal(view.settings.find(s=>s.key==='GUILDSYNC_GOOGLE_SHEETS_ENABLED').source,'.env');});
test('rejects unknown secrets, invalid dates, IDs and stale revisions without applying',async()=>{const service=createConfigurationService(memoryDB(),{env:{}});await service.initialize();await assert.rejects(service.save({revision:0,changes:{DISCORD_BOT_TOKEN:'secret'}}),/Unknown/);await assert.rejects(service.save({revision:0,changes:{GUILDSYNC_ONBOARDING_CHANNEL_ID:'bad'}}),/Discord ID/);await assert.rejects(service.save({revision:0,changes:{GUILDSYNC_GOOGLE_SHEETS_ROLLOVER_DELAY_HOURS:-1}}),/range/);await service.save({revision:0,changes:{GUILDSYNC_GOOGLE_SHEETS_ENABLED:true}});await assert.rejects(service.save({revision:0,changes:{GUILDSYNC_GOOGLE_SHEETS_ENABLED:false}}),/changed/);});
test('bot defaults report cannot overwrite backend values or stored overrides',async()=>{const service=createConfigurationService(memoryDB(),{env:{}});await service.initialize();await assert.rejects(service.registerBotDefaults({GUILDSYNC_GOOGLE_SHEETS_ENABLED:true}),/bot/);await service.registerBotDefaults({GUILDSYNC_RAFFLE_INTERVAL_HOURS:'72'});let view=await service.save({revision:0,changes:{GUILDSYNC_RAFFLE_INTERVAL_HOURS:24}});assert.equal(view.settings.find(s=>s.key==='GUILDSYNC_RAFFLE_INTERVAL_HOURS').defaultValue,72);assert.equal((await service.botConfiguration()).overrides.GUILDSYNC_RAFFLE_INTERVAL_HOURS,24);await service.registerBotDefaults({GUILDSYNC_RAFFLE_INTERVAL_HOURS:'48'});assert.equal((await service.botConfiguration()).overrides.GUILDSYNC_RAFFLE_INTERVAL_HOURS,24);assert.ok(configurationCatalog.every(s=>!s.key.includes('TOKEN')));});
test('enabled onboarding notifications require a channel and templates reject unknown placeholders',async()=>{const service=createConfigurationService(memoryDB(),{env:{}});await service.initialize();await assert.rejects(service.save({revision:0,changes:{GUILDSYNC_ONBOARDING_ENABLED:true}}),/channel/);await assert.rejects(service.save({revision:0,changes:{GUILDSYNC_ONBOARDING_PROMOTION_MESSAGE:'{secret}'}}),/placeholder/);});

test('socket authorization prevents users and bots from reading or saving admin settings',async()=>{const {registerConfigurationSocket}=await import('./admin-configuration-socket.js');const handlers=new Map();const socket={on:(k,v)=>handlers.set(k,v),guildSyncAuthenticated:true,guildSyncAuthType:'desktop',guildSyncUser:{discord_user_id:'123'}};let calls=0;registerConfigurationSocket(socket,{view(){calls++;return{};}},{authorizeAdmin:async()=>false});let response;await handlers.get('guildsync:request-admin-configuration')({},r=>response=r);assert.equal(response.ok,false);assert.equal(calls,0);socket.guildSyncAuthType='discord-bot';await handlers.get('guildsync:register-configuration-defaults')({},r=>response=r);assert.equal(response.ok,false);});

test('false bot defaults stay false and blank reminder/template overrides fail before save',async()=>{const service=createConfigurationService(memoryDB(),{env:{}});await service.initialize();await service.registerBotDefaults({GUILDSYNC_ONBOARDING_REMINDER_ENABLED:'false'});assert.equal(service.view().settings.find(s=>s.key==='GUILDSYNC_ONBOARDING_REMINDER_ENABLED').value,false);await assert.rejects(service.save({revision:0,changes:{GUILDSYNC_RAFFLE_BONUS_REMINDER_HOURS:''}}),/positive hours/);await assert.rejects(service.save({revision:0,changes:{GUILDSYNC_DEPOSIT_MAIL_BODY_TEMPLATE:''}}),/cannot be blank/);});
