// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CloseWindow():Promise<void>;

export function CollectGuildSyncBankingData(arg1:main.GuildSyncSavedVarsFileModifiedEvent):Promise<main.GuildSyncBankingDataResult>;

export function CommitGuildSyncBankingData(arg1:string,arg2:string):Promise<main.GuildSyncBankingDataResult>;

export function GetGuildSyncClientConfig():Promise<main.GuildSyncClientConfig>;

export function GetGuildSyncFileWatcherStatus():Promise<main.GuildSyncFileWatcherStatus>;

export function GetGuildSyncSession():Promise<main.GuildSyncSession>;

export function GetResolvedPaths():Promise<main.GuildSyncPaths>;

export function HideToTray():Promise<void>;

export function LogoutGuildSync():Promise<main.GuildSyncSession>;

export function MaximizeWindow():Promise<void>;

export function MinimizeWindow():Promise<void>;

export function QuitFromTray():Promise<void>;

export function SaveWindowState():Promise<void>;

export function SetGuildSyncSavedVarsWatchFileEnabled(arg1:string,arg2:boolean):Promise<main.GuildSyncFileWatcherStatus>;

export function ShowFromTray():Promise<void>;

export function ShowMainWindow():Promise<boolean>;

export function StartDiscordLogin():Promise<main.GuildSyncSession>;

export function StartGuildSyncFileWatcher():Promise<main.GuildSyncFileWatcherStatus>;

export function StopGuildSyncFileWatcher():Promise<main.GuildSyncFileWatcherStatus>;
