// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CleanupDepositMailAckFromGuildSyncBanking(arg1) {
  return window['go']['main']['App']['CleanupDepositMailAckFromGuildSyncBanking'](arg1);
}

export function CloseWindow() {
  return window['go']['main']['App']['CloseWindow']();
}

export function CollectDepositMailAckFromGuildSyncBanking(arg1) {
  return window['go']['main']['App']['CollectDepositMailAckFromGuildSyncBanking'](arg1);
}

export function CollectGuildSyncApplicationsData(arg1) {
  return window['go']['main']['App']['CollectGuildSyncApplicationsData'](arg1);
}

export function CollectGuildSyncBankingData(arg1) {
  return window['go']['main']['App']['CollectGuildSyncBankingData'](arg1);
}

export function CollectGuildSyncRosterData(arg1) {
  return window['go']['main']['App']['CollectGuildSyncRosterData'](arg1);
}

export function CommitGuildSyncApplicationsData(arg1, arg2) {
  return window['go']['main']['App']['CommitGuildSyncApplicationsData'](arg1, arg2);
}

export function CommitGuildSyncBankingData(arg1, arg2) {
  return window['go']['main']['App']['CommitGuildSyncBankingData'](arg1, arg2);
}

export function CommitGuildSyncRosterData(arg1, arg2) {
  return window['go']['main']['App']['CommitGuildSyncRosterData'](arg1, arg2);
}

export function FlushPendingDepositMailAckCleanup() {
  return window['go']['main']['App']['FlushPendingDepositMailAckCleanup']();
}

export function GetESORunningStatus() {
  return window['go']['main']['App']['GetESORunningStatus']();
}

export function GetGuildSyncClientConfig() {
  return window['go']['main']['App']['GetGuildSyncClientConfig']();
}

export function GetGuildSyncFileWatcherStatus() {
  return window['go']['main']['App']['GetGuildSyncFileWatcherStatus']();
}

export function GetGuildSyncSession() {
  return window['go']['main']['App']['GetGuildSyncSession']();
}

export function GetResolvedPaths() {
  return window['go']['main']['App']['GetResolvedPaths']();
}

export function HideToTray() {
  return window['go']['main']['App']['HideToTray']();
}

export function LogoutGuildSync() {
  return window['go']['main']['App']['LogoutGuildSync']();
}

export function MaximizeWindow() {
  return window['go']['main']['App']['MaximizeWindow']();
}

export function MinimizeWindow() {
  return window['go']['main']['App']['MinimizeWindow']();
}

export function QuitFromTray() {
  return window['go']['main']['App']['QuitFromTray']();
}

export function SaveWindowState() {
  return window['go']['main']['App']['SaveWindowState']();
}

export function SetGuildSyncSavedVarsWatchFileEnabled(arg1, arg2) {
  return window['go']['main']['App']['SetGuildSyncSavedVarsWatchFileEnabled'](arg1, arg2);
}

export function ShowFromTray() {
  return window['go']['main']['App']['ShowFromTray']();
}

export function ShowMainWindow() {
  return window['go']['main']['App']['ShowMainWindow']();
}

export function StartDiscordLogin() {
  return window['go']['main']['App']['StartDiscordLogin']();
}

export function StartGuildSyncFileWatcher() {
  return window['go']['main']['App']['StartGuildSyncFileWatcher']();
}

export function StopGuildSyncFileWatcher() {
  return window['go']['main']['App']['StopGuildSyncFileWatcher']();
}

export function WriteDepositMailToGuildSyncBanking(arg1) {
  return window['go']['main']['App']['WriteDepositMailToGuildSyncBanking'](arg1);
}
